### ISSUE TITLE
Schematic of the Panel and Control Board

### ISSUE THREAD

**Issue by italobbarros** [diyhue/DiyLeaf#2]
could you send the schematic of the panel to make it easier to understand?

**Comment by mariusmotea** [comment]
Sorry, i miss your request. Here is the main board project: https://easyeda.com/marius.motea/nanoleaf-control
And here is the panel project: https://oshwlab.com/marius.motea/NanoLeaf-ATtiny85

<blockquote><div><strong><a href="https://easyeda.com/marius.motea/nanoleaf-control">NanoLeaf control WS2812 -
    EasyEDA</a></strong></div></blockquote>
<blockquote><div><strong><a href="https://oshwlab.com/marius.motea/NanoLeaf-ATtiny85">NanoLeaf ATtiny85 - EasyEDA open source hardware lab</a></strong></div><div>In EasyEDA open source hardware lab, open source square pools all kinds of electrical design engineerings together to realize resource sharing easily.</div></blockquote>
