### ISSUE TITLE
how to control these.

### ISSUE THREAD

**Issue by jiveshd83** [diyhue/DiyLeaf#4]
Bro tell me how i can control these light panel by which software or website.

**Comment by mariusmotea** [comment]
DiyHue must be able to automatically detect these and control. Can you tell me what have you done so far?

**Comment by jiveshd83** [comment]
need to make diy hue to control these and plzz provide me the link of diy hue too

**Comment by mariusmotea** [comment]
https://github.com/diyhue/diyHue

Please note, this was not a finished product, but it was working during my last tests made one year ago. You need skills in electronics to build this.

<blockquote><img src="https://opengraph.githubassets.com/8716d8c6bd03df8220022658a4dbb6c9f9ec6955b55c6256f3b8e05e064fe4ec/diyhue/diyHue" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/diyhue/diyHue">GitHub - diyhue/diyHue: Main diyHue software repo</a></strong></div><div>Main diyHue software repo. Contribute to diyhue/diyHue development by creating an account on GitHub.</div></blockquote>

**Comment by jiveshd83** [comment]
can please provide me some screenshot of app controlling these

**Comment by mariusmotea** [comment]
No, i made some photos and are hard to find them after this period. The main issue of this project was the lack of the light diffuser.

**Comment by jiveshd83** [comment]
i have some idea for diffuser which you can use and complete these and plzz complete these for me bro.

**Comment by mariusmotea** [comment]
Will return home in few days. Let me see if I still have the stuff

**Comment by jiveshd83** [comment]
ok just check that and you can use some diffusing sheets and reflector films which is used in lcd tv or display.

**Comment by jiveshd83** [comment]
you can found all diffusing and reflector sheets in old lcd displays.
